### ISSUE TITLE
Implementation with MagicMirror Project

### ISSUE THREAD

**Issue by Ragziesoft** [hultenvp/soliscloud_api#6]
I have following questions.
1. Is it possible to implement this project with the Magic Mirror project.? I have obtained the API key and secret from Solis Cloud. The other value missing is NMI. What is this value, is it required.? 

2. Can you explain step by step how to execute this project on a Raspberry Pi. 

The soliscloud_api folder has to be in the test folder.

error while executing;
Traceback (most recent call last):
  File "/home/pi/soliscloud_api/test/test_public_methods.py", line 3, in <module>
    from .const import KEY, SECRET, NMI, VALID_RESPONSE
ImportError: attempted relative import with no known parent package
>>>

**Comment by andysu** [comment]
1 in docs - NMI required only for AU
